# Dockerfile.frontend
FROM nginx:alpine

# Copy angular dist-frontend into NGINX public directory
COPY ./dist-frontend/ /usr/share/nginx/html/

RUN echo ${PWD} && ls -lR

COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80